# Generated by Django 6.0 on 2025-12-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('contact', models.CharField(max_length=50)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
